version: '3'

# Services
services:

  mongo:
    image: mongo
    ports:
      - "27018:27017"
  
  redis:
    image: redis
    ports:
      - 6379:6379

  mynode:
    build: .
    ports:
    - "4040:4040"