version: '3'

# Services
services:

  mongo:
    image: mongo
    restart: on-failure
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

  api:
    image: wiki/apis
    hostname: user
    restart: on-failure
    build: ./services
    depends_on:
      - mongo
    ports:
      - "4040:4040"

volumes:
  mongodb-data:
