version: '3'

# Services
services:

  mongo:
    image: mongo
    restart: on-failure
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"

  api:
    image: wiki/apis
    hostname: api
    restart: on-failure
    build: ./services
    depends_on:
      - mongo
    links:
     - redis:redis
    ports:
      - "4040:4040"
      
  # admin:
  #   image: wiki/admin
  #   hostname: admin
  #   stdin_open: true
  #   restart: on-failure
  #   build: ./frontend/admin
  #   depends_on:
  #     - api
  #   ports:
  #     - 3100:3000
  


volumes:
  mongodb-data:
